# source ~/.bashrc
# # Get the aliases and functions

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

##
# Your previous /Users/matt/.bash_profile file was backed up as /Users/matt/.bash_profile.macports-saved_2011-07-09_at_15:05:49
##

# MacPorts Installer addition on 2011-07-09_at_15:05:49: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

